UrlSeguridad: "http://apiseguridadgalaxy:8080/",
ApiNameSeguridad: "apisender",
BusUrl: "Endpoint=sb://busgalaxyaaron.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=39uqcbg+zkiLJ0NC/9D8D6rGH49cA8+fNwspceR0q8Y=",
BusTopic: "pedidosender"
